%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Volumes/NO NAME/EBFBMBacox__ZT0to24_multiColumn.xlsx
%    Worksheet: Sleep (mins)
%
% Auto-generated by MATLAB on 01-Aug-2023 15:57:41

%% Set up the Import Options and import the data


%groupidx = find((T.Genotype == "R58H05_control_male"));


clear all
groups = ["acox_control_male",  "MB051B_control_male", "MB051B_acox_male" ];

opts = spreadsheetImportOptions("NumVariables", 6);

% Specify sheet and range
opts.Sheet = "Activity Counts Per min";
opts.DataRange = "A2:F786";

% Specify column names and types
opts.VariableNames = ["Genotype", "ExpRow", "Day1", "Day2", "Day3", "VarName6"];
opts.VariableTypes = ["categorical", "double", "double", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, "Genotype", "EmptyFieldRule", "auto");

% Import the data
T= readtable("/Volumes/NO NAME/EBFBMBacox__ZT0to24_multiColumn.xlsx", opts, "UseExcel", false);

%%
for i = 1: length(groups)
    groupidx = find((T.Genotype == groups(i)));
    data = zeros(length(groupidx), 4);
    data(:,1) = T.Day1(groupidx);
    data(:,2) = T.Day2(groupidx);
    data(:,3) = T.Day3(groupidx);
    data(:,4) = mean(data(:,1:3),2)
    final{i} = data(:,4);
    if i == 1
        RNAictrl = table(data(:,4));
    elseif i == 2
        Gal4ctrl = table(data(:,4));
    else i == 3
        exp = table(data(:,4));
    end
end


